# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions


on:
  schedule:
    - cron:  '0 0 * * *'

name: update
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}


jobs:
  BOE:
    if: "! contains(github.event.commits.*.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install system dependencies
        run:  sudo apt-get install libcurl4-openssl-dev
      - name: Cache R packages # From https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml#L50-L56
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}--
      - name: Install dependencies
        # if: ${{ failure() }} # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif
        run: |
          Rscript -e "install.packages(c('future.apply'))"
      - name: git config
        run: |
          git config --global user.email 'actions@github.com'
          git config --global user.name 'gh-pages committer'
      - name: Update data
        run: Rscript save.R
      - name: Commit results
        run: |
          git add *.RDS *.in || git commit -a -m 'Automatic commit to update data'
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.APPTOKEN }}
